### ISSUE TITLE
Nettle version 

### ISSUE THREAD

**Issue by oleg22716** [BioTurboNick/Scrypt.jl#1]
That's on Julia 1.5's alpine image 

julia_1  | ERROR: LoadError: could not load library "libnettle.so.6"
julia_1  | Error loading shared library libnettle.so.6: No such file or directory
julia_1  | Stacktrace:
julia_1  |  [1] get_hash_types() at /root/.julia/packages/Nettle/LhcpB/src/hash_common.jl:51
julia_1  |  [2] Nettle.HMACState(::String, ::Array{UInt8,1}) at /root/.julia/packages/Nettle/LhcpB/src/hmac.jl:17
julia_1  |  [3] digest(::String, ::Array{UInt8,1}, ::Array{UInt8,1}) at /root/.julia/packages/Nettle/LhcpB/src/hmac.jl:50
julia_1  |  [4] pbkdf2_sha256_1(::Array{UInt8,1}, ::Array{UInt8,1}, ::Int64) at /root/.julia/packages/Scrypt/3lhM6/src/Scrypt.jl:36
julia_1  |  [5] scrypt(::ScryptParameters, ::Array{UInt8,1}, ::Array{UInt8,1}, ::Int64) at /root/.julia/packages/Scrypt/3lhM6/src/Scrypt.jl:12
julia_1  |  [6] macro expansion at ./timing.jl:310 [inlined]
julia_1  |  [7] measure() at /jl1/src/jl/main.jl:7
julia_1  |  [8] top-level scope at /jl1/src/jl/main.jl:19
julia_1  |  [9] include(::Function, ::Module, ::String) at ./Base.jl:380
julia_1  |  [10] include(::Module, ::String) at ./Base.jl:368
julia_1  |  [11] exec_options(::Base.JLOptions) at ./client.jl:296
julia_1  |  [12] _start() at ./client.jl:506
julia_1  | in expression starting at /jl1/src/jl/main.jl:19
Not sure, what I should do with all that. 
Manually adding package won't fix the problem. There are nettle.so.5 and .so.7 files in that pkg
I'm kinda new and might be missing something, but it just does not work

**Comment by BioTurboNick** [comment]
Hmm... I'll take a look. In the meantime you might find some tips on discourse.julialang.org for similar situations? I developed on Windows and a WSL Ubuntu, not familiar with Alpine.

**Comment by oleg22716** [comment]
Sorry. I think rather it's the problem of Pkg. All stuff should be made with tarballz. Until then, switchin to Elixir. Julia wasn't the right choice for backend anyways
